version: '3.8'
services:
  openrouteservice:
    container_name: OpenRouteService
    image: izone/openrouteservice:v6.2.0
    networks:
      - osm
    ports:
      - 8989:8080
    volumes:
      - graphs:/ors-core/data/graphs
      - elevation_cache:/ors-core/data/elevation_cache
      - logs_ors:/var/log/ors
      - logs_tomcat:/usr/local/tomcat/logs
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms4g -Xmx8g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
    restart: always
      
networks:
  osm:
  
volumes:
  graphs:
  elevation_cache:
  logs_ors:
  logs_tomcat:
